# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4522a586e2b5f4907b451ee8ff7e30af"
name = "stg-contact-form-app"
handle = "stg-contact-form-app"
application_url = "https://stg-easy-contact-form.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "easycontactform-staging.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://stg-easy-contact-form.vercel.app/auth/callback",
  "https://stg-easy-contact-form.vercel.app/auth/shopify/callback",
  "https://stg-easy-contact-form.vercel.app/api/auth/callback",
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
